name: xiaowang
favicon: null
layout_spectrum: 0.03418312733992934
typography_spectrum: 0.6349806191865355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.985322950175032
  lightness: 0.9484878352377564
  saturation: 0.9654007537756115
  rhythmicContrast: 0.891952776350081
purpose: []
